/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205715;
import java.util.Scanner;
public class Main{
    static String[][] masterBord = { { "・", "・", "・", "・", "・" }, { "・", "・", "・", "・", "・" },
            { "・", "・", "・", "・", "・" }, { "・", "・", "・", "・", "・" }, { "・", "・", "・", "・", "・" } };

    static boolean victory = false;

    static String[] victoryBord = { "○", "○", "○", "○", "○" };
  
    public static void bordOut() {
        for (int i = 0; i < 5; i++) {
            for (int e = 0; e<5; e++){ 
                System.out.print(masterBord[i][e]); 
            }
            System.out.println();
        }
    }
    
    public static void judge(){
        int countYoko = 0;
        int countTate = 0;
        int countNaname1 = 0;
        int countNaname2 = 0;
        for (int i = 0; i < 5; i++) {
            for (int e = 0; e<5; e++){
                if (masterBord[i][e] == "○" ) {
                    countYoko += 1;
                }
                if (countYoko == 5){
                    victory = true;
                }
            }
            countYoko = 0;
        }
        for (int i = 0; i<5; i++){
            for (int e = 0; e<5; e++){
                if (masterBord[e][i] == "○" ) {
                    countTate += 1;
                }
                if (countTate == 5){
                    victory = true;
                }
            }
            countTate = 0;
        }
        for (int i = 0; i<5; i++){
            if (masterBord[i][i] == "○"){
                countNaname1 += 1;
            }
            if (countNaname1 == 5){
                victory = true;
            }
        }
        for(int i=0,e=4; i<5; i++,e--){
            if (masterBord[i][e] == "○"){
                countNaname2 += 1;
            }
            if (countNaname2 == 5){
                victory = true;
            }
        }
    }
    public static void main(String[]args){
        bordOut();
        while(victory == false){
            System.out.println("行数を入力してください");
            Scanner scanYoko = new Scanner(System.in);
            int yoko = scanYoko.nextInt();
            System.out.println("列数を入力してください");
            Scanner scanTate = new Scanner(System.in);
            int tate = scanTate.nextInt();
            masterBord[yoko-1][tate-1] = "○";
            bordOut();
            judge();
            if (victory == true){
                scanYoko.close();
                scanTate.close();
            }
        }
    }
    /*
	public Object getGreeting() {
		return null;
    }
    */
}